### ISSUE TITLE
rem.darwin mouse pointer y limited to system frame

### ISSUE THREAD

**Issue by luarockr** [io-core/io#3]
running io on a MBP under macOS 10.14.2 limits vertical mouse movements to the size of the system frame (upper right), cannot move lower than that.

**Comment by charlesap** [comment]
Does this mac have a Retina display?
rem.darwin has a -hidpi option, not sure if it is pushed to the built binary yet. Will check.

**Comment by luarockr** [comment]
Yes, it has a Retina display. The -hidpi option works properly. Thanks for the hint :)
