### ISSUE TITLE
rem.darwin excessive cpu load

### ISSUE THREAD

**Issue by luarockr** [io-core/io#4]
running on MBP under macOS 10.14.2 io utilizes in idle approx. 150% CPU time (multi core).

**Comment by charlesap** [comment]
Idle detection is not implemented yet... soon though.

**Comment by charlesap** [comment]
rough implementation if idle detection is in... but could be better. CPU use is now 25% on Linux and 75% on Mac (on my machines.)

**Comment by schierlm** [comment]
You can get the CPU load down extremely by having the Oberon main loop report the start time of the next task via MMIO to the emulator: https://github.com/schierlm/OberonEmulator/blob/master/Oberon/power-management.patch

Of course that does not help during bootup or when the system is not patched, but for my JavaScript emulator this is a lifesaver having the system to idle for 1 second usually before GC triggers again.

**Comment by charlesap** [comment]
Issue closed as I have ceased development on the rem emulator. This emulator https://github.com/pdewacht/oberon-risc-emu is an excellent alternative.
